spring:
    datasource:
            url: jdbc:postgresql://localhost:5432/pointdafamilia
            username: postgres
            password: 123456
            driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        open-in-view: false
        
        